INSERT into product_service_schema.products (name, description)
VALUES ('A', ''),
       ('AA', ''),
       ('AAA', ''),
       ('AAAA', ''),
       ('AAAAA', ''),
       ('B', ''),
       ('BB', ''),
       ('BBB', ''),
       ('BBBB', ''),
       ('BBBBB', ''),
       ('C', ''),
       ('CC', ''),
       ('CCC', ''),
       ('CCCC', ''),
       ('CCCCC', ''),
       ('D', ''),
       ('DD', ''),
       ('DDD', ''),
       ('DDDD', ''),
       ('DDDDD', ''),
       ('AB', ''),
       ('ABC', ''),
       ('ABCD', ''),
       ('BC', ''),
       ('BCD', ''),
       ('A A', ''),
       ('B B', ''),
       ('C C', ''),
       ('D D', ''),
       ('Aa', ''),
       ('Bb', ''),
       ('Cc', ''),
       ('Dd', ''),
       ('aa', ''),
       ('bb', ''),
       ('cc', ''),
       ('dd', ''),
       ('abcd1', ''),
       ('bcd2', ''),
       ('cd3', '')
ON CONFLICT DO NOTHING;


