INSERT into product_service_schema.products (name, description)
VALUES ('Absolute Glam', ''),
       ('Aesthetic Idols', ''),
       ('Aesthetic Storm', ''),
       ('Allure Beauty Cruise', ''),
       ('BareBeauty Cosmetics', ''),
       ('Beauty Moon', ''),
       ('Become Aesthetic', ''),
       ('Bee Pretty', ''),
       ('Be Lovely', ''),
       ('Beyond Heaven', ''),
       ('Blooming Beauty', ''),
       ('Budget Cosmetics', ''),
       ('Careful Cosmetics', ''),
       ('Cherish Life Society', ''),
       ('Cosmetics Den', ''),
       ('Cosmetic Queens', ''),
       ('Cosmoline', ''),
       ('Crimson Cosmetics', ''),
       ('Crush Cosmetics Inc', ''),
       ('Desire Face', ''),
       ('Dream Shades', ''),
       ('Ethereal Enhancement', ''),
       ('Everything Nice', ''),
       ('Fabulous Baby!', ''),
       ('Face Artistry', ''),
       ('Fox Cosmetics', ''),
       ('Frosted Cosmetics', ''),
       ('Glow Away', ''),
       ('Glow and Go', ''),
       ('Lavish Enhancement', ''),
       ('Glow Girl Blush', ''),
       ('Hook', ''),
       ('Little Angel Cosmetics', ''),
       ('Lip Gloss Veneer Inc.', ''),
       ('Lippy Time', ''),
       ('Magic drop', ''),
       ('Marshmellow Beauty Inc.', ''),
       ('Makeup Bomb', ''),
       ('Ultra Beauty', ''),
       ('Zestful Queen', '')
ON CONFLICT DO NOTHING;